
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Simbolo_divi = 6;
  public static final int numero = 7;
  public static final int error = 1;
  public static final int Simbolo_menos = 4;
  public static final int Simbolo_multi = 5;
  public static final int punto_coma = 2;
  public static final int Simbolo_mas = 3;
  public static final int EOF = 0;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "punto_coma",
  "Simbolo_mas",
  "Simbolo_menos",
  "Simbolo_multi",
  "Simbolo_divi",
  "numero"
  };
}

